# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-12 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_delete_userwechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[(b'news', 'news'), (b'policy and information', 'policy and information'), (b'organization and position responsibility', 'organization and position responsibility'), (b'road risk map', 'road risk map')], default=b'news', max_length=150, null=True, verbose_name=b'title'),
        ),
    ]
