# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-18 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'artical', 'verbose_name_plural': 'artical'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'banner', 'verbose_name_plural': 'banner'},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[(b'news', 'news'), (b'policy_and_information', 'policy and information'), (b'organization_and_position_responsibility', 'organization and position responsibility'), (b'road_risk_map', 'road risk map')], default=b'news', max_length=150, null=True, verbose_name=b'title'),
        ),
    ]
