# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import newsletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_auto_20171118_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[(b'news', 'news'), (b'policy_and_information', 'policy and information'), (b'organization_and_position_responsibility', 'organization and position responsibility'), (b'road_risk_map', 'road risk map')], default=b'news', max_length=150, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=newsletter.models.image_upload_to_article, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publishtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='publishtime'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to=newsletter.models.image_upload_to_banner, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='title'),
        ),
    ]
