# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-17 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0012_auto_20171214_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(default='', max_length=120, verbose_name='title'),
            preserve_default=False,
        ),
    ]
