# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-27 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0002_auto_20171027_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forkliftannualinspectionimage',
            old_name='forklift',
            new_name='forklift_annual_inspection',
        ),
    ]
