# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-27 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0005_auto_20171027_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forklift',
            name='fork_length',
        ),
        migrations.AddField(
            model_name='forklift',
            name='forklift_length',
            field=models.CharField(default=1, max_length=30, verbose_name='Forklift Length'),
            preserve_default=False,
        ),
    ]
