# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-27 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0006_auto_20171027_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forkliftrepair',
            name='description',
            field=models.TextField(max_length=30, verbose_name='Breakdown Description'),
        ),
    ]
