# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-01 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0008_auto_20171029_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('driver_ID', models.CharField(max_length=30, verbose_name='Driver ID')),
                ('driver_license_type', models.CharField(max_length=30, verbose_name='driver license type')),
                ('DDC_certificate_number', models.CharField(max_length=30, verbose_name='DDC certificate number')),
                ('certificate_issued_time', models.DateField(verbose_name='certificate issued time')),
                ('certificate_valid_until', models.DateField(verbose_name='certificate valid until')),
                ('first_licensed_time', models.DateField(verbose_name='first licensed time')),
                ('driving_years', models.PositiveIntegerField(verbose_name='dirving years')),
                ('driver_license_valid_until', models.DateField(verbose_name='driver license valid until')),
                ('contact_phone', models.CharField(max_length=30, verbose_name='contact phone')),
                ('training_qualified', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='contact phone')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_content', models.CharField(choices=[('shuttle bus', 'shuttle bus'), ('truck', 'truck'), ('dangerous goods vehicles', 'dangerous goods vehicles'), ('scattered oil vehicles', 'scattered oil vehicles')], max_length=130, verbose_name='service content')),
                ('motorcade', models.CharField(max_length=30, verbose_name='motorcade')),
                ('relevant_license_plate', models.CharField(max_length=30, verbose_name='relevant license plate')),
                ('vehicle_inspection_valid_until', models.DateField(verbose_name='vehicle inspection valid until')),
                ('vehicle_type', models.CharField(max_length=30, verbose_name='vehicle type')),
                ('relevant_trailer_number', models.CharField(max_length=30, verbose_name='relevant trailer number')),
                ('trailer_inspection_valid_until', models.DateField(verbose_name='trailer inspection valid until')),
                ('maximum_loadable_tonnage', models.PositiveIntegerField(verbose_name='maximum loadable tonnage')),
                ('green_mark_valid_until', models.DateField(verbose_name='green mark valid until')),
                ('insurance_policy_valid_until', models.DateField(verbose_name='insurance policy valid until')),
                ('GPS', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='GPS')),
                ('ABS', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='ABS')),
                ('antiroll_protection', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='antiroll protection')),
                ('reversing_alarm', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='reversing alarm')),
                ('side_edge_and_low_location_collision_guard_bar', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='side edge and low location collision guard bar')),
                ('car_seat_headrest', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='car seat headrest')),
                ('three_point_belt', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='three-point belt')),
                ('IVMS_or_VDR', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='IVMS or VDR')),
                ('anti_drop_equipment', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='anti-drop equipment')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_inspection', models.DateField(verbose_name='Date of Inspection')),
                ('inspector', models.CharField(max_length=30, verbose_name='Inspector')),
                ('carrier', models.CharField(max_length=30, verbose_name='carrier')),
                ('disqualification_comments', models.TextField(max_length=300, verbose_name='disqualification comments')),
                ('rectification_qualified', models.CharField(max_length=30, verbose_name='Rectification qualified')),
                ('hardware_inspection_disqualification', models.CharField(max_length=30, verbose_name='hardware inspection disqualification')),
                ('no_driver_code_of_conduct', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='no driver code of conduct')),
                ('overload_or_LSR_violation', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='overload or LSR violation')),
                ('safety_policy_violation', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='safety policy violation')),
                ('no_journey_plan_or_log', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='no journey plan or log')),
                ('vehichle_not_register', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='vehichle not register')),
                ('no_vehicle_inspection_record', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='no vehicle inspection record')),
                ('no_DDC_certificate', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='no DDC certificate')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outsourcing.Driver', verbose_name='driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outsourcing.Vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'vehicle inspection',
                'verbose_name_plural': 'vehicle inspection',
            },
        ),
        migrations.CreateModel(
            name='VehicleTransportationKPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation_project', models.CharField(choices=[('shuttle bus', 'shuttle bus'), ('general cargo shanghai', 'general cargo shanghai'), ('general cargo zhejiang', 'general cargo zhejiang'), ('scattered oil (land-and-water coordinated transport)', 'scattered oil (land-and-water coordinated transport)'), ('scattered oil (road)', 'Scattered oil (road)'), ('hazardous article', 'hazardous article'), ('water transport', 'water transport')], max_length=30, verbose_name='transportation project')),
                ('year', models.CharField(max_length=30, verbose_name='year')),
                ('month', models.CharField(max_length=30, verbose_name='month')),
                ('safe_mileages', models.PositiveIntegerField(verbose_name='safe mileage')),
                ('safe_labor_hours', models.PositiveIntegerField(verbose_name='safe labor hours')),
                ('LSR_violation_cases', models.PositiveIntegerField(verbose_name='LSR violation cases')),
                ('safety_accident_cases', models.PositiveIntegerField(verbose_name='safety accident cases')),
                ('yearly_plan_executing_rate', models.CharField(max_length=30, verbose_name='yearly plan executing rate')),
                ('vehicle_qualification_rate', models.CharField(max_length=30, verbose_name='vehicle qualification rate')),
                ('journey_management_rules_implemented_rate', models.CharField(max_length=30, verbose_name='journey management rules implemented rate')),
                ('safe_loading_violation_cases', models.PositiveIntegerField(verbose_name='safe loading violation cases')),
                ('departure_count', models.PositiveIntegerField(verbose_name='departure count')),
                ('departure_tones', models.PositiveIntegerField(verbose_name='departure tones')),
                ('monthly_delivery_plan_completion_rate', models.CharField(max_length=30, verbose_name='monthly delivery plan completion rate')),
                ('AOG_on_time_rate', models.CharField(max_length=30, verbose_name='AOG on-time rate')),
                ('POD_on_time_rate', models.CharField(max_length=30, verbose_name='POD On-Time rate')),
                ('POD_accuracy', models.CharField(max_length=30, verbose_name='POD accuracy')),
                ('customer_satisfaction_rate', models.CharField(max_length=30, verbose_name='customer satisfaction rate')),
                ('customer_complaint_cases', models.CharField(max_length=30, verbose_name='Customer complaint cases')),
            ],
            options={
                'verbose_name': 'vehicle tranportation KPI',
                'verbose_name_plural': 'vehicle tranportation KPI',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outsourcing.Vehicle', verbose_name='vehicle'),
        ),
    ]
