# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-01 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0009_auto_20171101_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'driver', 'verbose_name_plural': 'drivers'},
        ),
        migrations.AlterField(
            model_name='driver',
            name='training_qualified',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='training qualified'),
        ),
    ]
