# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-04 06:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0010_auto_20171101_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletransportationkpi',
            name='month',
            field=models.CharField(choices=[(b'1jan', 'January'), (b'2feb', 'February'), (b'3mar', 'March'), (b'4apr', 'April'), (b'5may', 'May'), (b'6jun', 'June'), (b'7jul', 'July'), (b'8aug', 'August'), (b'9sep', 'September'), (b'aoct', 'October'), (b'bnov', 'November'), (b'cdev', 'December')], max_length=30, verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='vehicletransportationkpi',
            name='year',
            field=models.PositiveIntegerField(help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(2017), django.core.validators.MaxValueValidator(2017)], verbose_name='year'),
        ),
    ]
