# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-04 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import inspection.utils


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0012_auto_20171104_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletransportationkpi',
            name='AOG_on_time_rate',
            field=inspection.utils.PercentageField(max_length=30, verbose_name='AOG on-time rate'),
        ),
        migrations.AlterField(
            model_name='vehicletransportationkpi',
            name='POD_accuracy',
            field=inspection.utils.PercentageField(max_length=30, verbose_name='POD accuracy'),
        ),
        migrations.AlterField(
            model_name='vehicletransportationkpi',
            name='POD_on_time_rate',
            field=inspection.utils.PercentageField(max_length=30, verbose_name='POD On-Time rate'),
        ),
        migrations.AlterField(
            model_name='vehicletransportationkpi',
            name='customer_complaint_cases',
            field=models.PositiveIntegerField(max_length=30, verbose_name='Customer complaint cases'),
        ),
        migrations.AlterField(
            model_name='vehicletransportationkpi',
            name='customer_satisfaction_rate',
            field=inspection.utils.PercentageField(max_length=30, verbose_name='customer satisfaction rate'),
        ),
        migrations.AlterField(
            model_name='vehicletransportationkpi',
            name='journey_management_rules_implemented_rate',
            field=inspection.utils.PercentageField(max_length=30, verbose_name='journey management rules implemented rate'),
        ),
        migrations.AlterField(
            model_name='vehicletransportationkpi',
            name='monthly_delivery_plan_completion_rate',
            field=inspection.utils.PercentageField(max_length=30, verbose_name='monthly delivery plan completion rate'),
        ),
        migrations.AlterField(
            model_name='vehicletransportationkpi',
            name='yearly_plan_executing_rate',
            field=inspection.utils.PercentageField(max_length=30, verbose_name='yearly plan executing rate'),
        ),
    ]
