# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-04 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0013_auto_20171104_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletransportationkpi',
            name='customer_complaint_cases',
            field=models.PositiveIntegerField(verbose_name='Customer complaint cases'),
        ),
    ]
