# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-05 07:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0014_auto_20171104_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletransportationkpi',
            name='month',
            field=models.CharField(choices=[(b'01', 'January'), (b'02', 'February'), (b'03', 'March'), (b'04', 'April'), (b'05', 'May'), (b'06', 'June'), (b'07', 'July'), (b'08', 'August'), (b'09', 'September'), (b'10', 'October'), (b'11', 'November'), (b'12', 'December')], max_length=30, verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='vehicletransportationkpi',
            name='transportation_project',
            field=models.CharField(choices=[('shuttle bus', 'shuttle bus'), ('general cargo shanghai', 'general cargo shanghai'), ('general cargo zhejiang', 'general cargo zhejiang'), ('scattered oil (land-and-water coordinated transport)', 'scattered oil (land-and-water coordinated transport)'), ('scattered oil (road)', 'Scattered oil (road)'), ('hazardous article', 'hazardous article'), ('water transport', 'water transport')], max_length=130, verbose_name='transportation project'),
        ),
        migrations.AlterField(
            model_name='vehicletransportationkpi',
            name='year',
            field=models.PositiveIntegerField(help_text='Use the following format: < YYYY >', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2017)], verbose_name='year'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicletransportationkpi',
            unique_together=set([('year', 'month', 'transportation_project')]),
        ),
    ]
