# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-11 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0015_auto_20171105_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletransportationkpi',
            name='customer_satisfaction_rate',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='customer satisfaction rate'),
        ),
    ]
