# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-11 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0016_auto_20171111_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicletransportationkpi',
            name='customer_satisfaction_rate',
        ),
    ]
