# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-04 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0018_vehicletransportationkpi_customer_satisfaction_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='motorcade',
        ),
        migrations.AddField(
            model_name='driver',
            name='motorcade',
            field=models.CharField(default='', max_length=30, verbose_name='motorcade'),
            preserve_default=False,
        ),
    ]
