# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-09 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0020_remove_driver_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='owner',
            field=models.CharField(default='', max_length=30, verbose_name='Owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forkliftrepair',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Discovered Date'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='date_of_inspection',
            field=models.DateField(auto_now_add=True, verbose_name='Date of Inspection'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='hardware_inspection_disqualification',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='hardware inspection disqualification'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='rectification_qualified',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='Rectification qualified'),
        ),
    ]
