# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-09 04:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0022_auto_20171209_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rectification completed time'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 9, 4, 45, 16, 176000, tzinfo=utc), verbose_name='Due Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='load_or_unload',
            field=models.CharField(choices=[('load', 'load cargo'), ('unload', 'unload cargo')], default='load', max_length=30, verbose_name='load or unload'),
        ),
    ]
