# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-09 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0023_auto_20171209_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='forkliftrepair',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
    ]
