# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-09 06:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0024_auto_20171209_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='forkliftrepair',
            name='owner',
            field=models.CharField(default="", max_length=30, verbose_name='Owner'),
            preserve_default=False,
        ),
    ]
