# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-09 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0025_forkliftrepair_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forkliftrepair',
            name='repaire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Repaire Date'),
        ),
    ]
