# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-09 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0026_auto_20171209_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forkliftrepair',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
    ]
