# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-16 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0028_auto_20171216_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forklift',
            name='internal_car_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Inner Car Number'),
        ),
    ]
