# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-16 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0029_auto_20171216_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forkliftrepair',
            name='repaired',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=30, verbose_name='Repaired'),
        ),
    ]
