# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-16 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0030_auto_20171216_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forkliftrepair',
            name='accessories_name',
            field=models.CharField(max_length=30, verbose_name='Accessories Name'),
        ),
        migrations.AlterField(
            model_name='forkliftrepair',
            name='accessories_num',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Accessories Number'),
        ),
        migrations.AlterField(
            model_name='forkliftrepair',
            name='damage_reason',
            field=models.CharField(max_length=30, verbose_name='Damage Reason'),
        ),
    ]
