# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-18 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0031_auto_20171216_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinspection',
            name='hardware_inspection_disqualification',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=30, verbose_name='hardware inspection disqualification'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='no_DDC_certificate',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=30, verbose_name='no DDC certificate'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='no_driver_code_of_conduct',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=30, verbose_name='no driver code of conduct'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='no_journey_plan_or_log',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=30, verbose_name='no journey plan or log'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='no_vehicle_inspection_record',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=30, verbose_name='no vehicle inspection record'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='overload_or_LSR_violation',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=30, verbose_name='overload or LSR violation'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='rectification_qualified',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=30, verbose_name='Rectification qualified'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='safety_policy_violation',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=30, verbose_name='safety policy violation'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='vehichle_not_register',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=30, verbose_name='vehichle not register'),
        ),
    ]
