# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-30 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0033_auto_20171219_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='forkliftmaint',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Expenser'),
        ),
        migrations.AddField(
            model_name='forkliftrepair',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Expenser'),
        ),
    ]
