# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-01 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcing', '0036_auto_20180101_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleinspection',
            old_name='date_of_inspection',
            new_name='created',
        ),
    ]
