# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-17 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0033_spraypumproominspection_indicator_and_instrument_normal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spraypumproominspection',
            options={'ordering': ('month',)},
        ),
        migrations.AlterField(
            model_name='shelf_inspection_record',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.shelf', verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='spraypumproominspection',
            name='month',
            field=models.CharField(choices=[(b'1jan', 'January'), (b'2feb', 'February'), (b'3mar', 'March'), (b'4apr', 'April'), (b'5may', 'May'), (b'6jun', 'June'), (b'7jul', 'July'), (b'8aug', 'August'), (b'9sep', 'September'), (b'aoct', 'October'), (b'bnov', 'November'), (b'cdev', 'December')], max_length=30, verbose_name='Month'),
        ),
    ]
