# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-22 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0034_auto_20171017_2323'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='electricalequipmentinspection',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='electricalequipmentinspection',
            name='equipment',
        ),
        migrations.DeleteModel(
            name='ElectricalEquipmentInspection',
        ),
        migrations.DeleteModel(
            name='equipment',
        ),
    ]
