# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-26 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0035_auto_20171022_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spraypumproominspection',
            options={'ordering': ('month',), 'verbose_name': 'Spray Pump Room Inspection', 'verbose_name_plural': 'Spray Pump Room Inspection'},
        ),
        migrations.AddField(
            model_name='spraypumproominspection',
            name='date_of_inspection',
            field=models.DateField(default=b'1970-01-01', null=True, verbose_name='Date of Inspection'),
        ),
        migrations.AddField(
            model_name='spraypumproominspection',
            name='inspector',
            field=models.CharField(default='', max_length=30, verbose_name='Inspector'),
            preserve_default=False,
        ),
    ]
