# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-26 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0036_auto_20171026_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spraypumproominspection',
            name='date_of_inspection',
            field=models.DateField(default=b'1970-01-01', verbose_name='Date of Inspection'),
        ),
    ]
