# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-01 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0038_auto_20171027_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extinguisher_inspection',
            name='extinguisher',
        ),
        migrations.RemoveField(
            model_name='hydrant_inspection',
            name='extinguisher',
        ),
        migrations.DeleteModel(
            name='extinguisher',
        ),
        migrations.DeleteModel(
            name='extinguisher_inspection',
        ),
        migrations.DeleteModel(
            name='hydrant',
        ),
        migrations.DeleteModel(
            name='hydrant_inspection',
        ),
    ]
