# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-01 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0039_auto_20171101_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rehearsal',
            options={'verbose_name': 'rehearsal', 'verbose_name_plural': 'rehearsal'},
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='title',
            field=models.CharField(blank=True, max_length=30, verbose_name='Title'),
        ),
    ]
