# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-01 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0040_auto_20171101_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='PI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Annual Inspection Date')),
                ('reporter', models.CharField(max_length=30, verbose_name='reporter')),
                ('company_of_reporter', models.CharField(max_length=30, verbose_name='company of reporter')),
                ('department_of_reporter', models.CharField(choices=[(b'safety', b'safety'), (b'storage', b'storage'), (b'administration', b'administration')], max_length=30, verbose_name='department of reporter')),
                ('report_content', models.CharField(max_length=30, verbose_name='report content')),
                ('PI_area', models.CharField(max_length=30, verbose_name='PI area')),
                ('category', models.CharField(max_length=30, verbose_name='category')),
                ('risk', models.CharField(max_length=30, verbose_name='risk')),
                ('direct_reason', models.CharField(max_length=30, verbose_name='direct reason')),
                ('root_cause', models.CharField(max_length=30, verbose_name='root cause')),
                ('feedback_person', models.CharField(max_length=30, verbose_name='feedback person')),
                ('rectification_measures', models.CharField(max_length=30, verbose_name='rectification measures')),
                ('planned_complete_date', models.DateField(verbose_name='planned complete date')),
                ('rectification_status', models.CharField(max_length=30, verbose_name='rectification status')),
                ('close_person', models.CharField(max_length=30, verbose_name='close person')),
                ('picture_before_rectification', models.CharField(max_length=30, verbose_name='picture before rectification')),
                ('picture_after_rectification', models.CharField(max_length=30, verbose_name='picture after rectification')),
            ],
            options={
                'verbose_name': 'PI',
                'verbose_name_plural': 'PI',
            },
        ),
    ]
