# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-01 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0041_pi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SprayPumpRoomInspection',
        ),
    ]
