# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-12 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0042_delete_spraypumproominspection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfAnnualInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Annual Inspection Date')),
                ('next_date', models.DateField(verbose_name='Next Inspection Date')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.shelf', verbose_name='shelf')),
            ],
            options={
                'verbose_name': 'shelf annual inspection',
                'verbose_name_plural': 'shelf annual inspection',
            },
        ),
        migrations.AlterField(
            model_name='shelf_inspection_record',
            name='shelf_inspection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inspection.shelf_inspection', verbose_name='shelf inspection'),
        ),
    ]
