# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-15 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0044_auto_20171112_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_import_file', models.FileField(upload_to=b'upload/shelf_excel', verbose_name='shelf import file')),
            ],
            options={
                'ordering': ['shelf_import_file'],
            },
        ),
    ]
