# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-18 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0045_shelfimport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelfimport',
            options={'ordering': ['shelf_import_file'], 'verbose_name': 'shelf import', 'verbose_name_plural': 'shelf import'},
        ),
    ]
