# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0046_auto_20171118_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehearsal',
            name='attachment',
            field=models.FileField(blank=True, upload_to=b'rehearsal', verbose_name='Attachment'),
        ),
    ]
