# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-25 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0047_auto_20171121_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyinspection',
            name='rectification_measures',
            field=models.TextField(max_length=500, verbose_name='Rectification Measures'),
        ),
    ]
