# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-26 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0048_auto_20171125_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyinspection',
            name='completed_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 26, 11, 27, 44, 362000, tzinfo=utc), verbose_name='completed time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyinspection',
            name='inspector',
            field=models.CharField(default='', max_length=30, verbose_name='Inspector'),
            preserve_default=False,
        ),
    ]
