# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-26 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0049_auto_20171126_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyinspection',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='inspection completed time'),
        ),
    ]
