# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-26 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0050_auto_20171126_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyinspection',
            name='inspector',
        ),
    ]
