# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-02 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0055_auto_20171202_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInspectionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=300, verbose_name='log')),
                ('dailyinpsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.DailyInspection', verbose_name='Daily Inspection')),
            ],
        ),
    ]
