# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-02 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0057_remove_dailyinspectionlog_dailyinpsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyinspectionlog',
            name='dailyinspection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inspection.DailyInspection', verbose_name='Daily Inspection'),
            preserve_default=False,
        ),
    ]
