# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-03 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0058_dailyinspectionlog_dailyinspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehearsal',
            name='image',
            field=models.FileField(blank=True, upload_to=b'rehearsal', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='shelf_inspection_record',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rectification completed time'),
        ),
        migrations.AddField(
            model_name='shelf_inspection_record',
            name='owner',
            field=models.CharField(default='', max_length=30, verbose_name='Owner'),
            preserve_default=False,
        ),
    ]
