# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-03 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0059_auto_20171203_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehearsal',
            name='image',
            field=models.FileField(blank=True, upload_to=b'rehearsal', verbose_name='image'),
        ),
    ]
