# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-07 08:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0060_auto_20171203_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf_inspection_record',
            name='check_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 12, 7, 8, 46, 57, 422000, tzinfo=utc), verbose_name='Check Date'),
            preserve_default=False,
        ),
    ]
