# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-07 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0061_shelf_inspection_record_check_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf_inspection_record',
            name='forecast_complete_time',
            field=models.DateField(blank=True, null=True, verbose_name='Forecast Complete Time'),
        ),
    ]
