# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-09 13:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import inspection.models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0062_auto_20171207_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pi',
            options={'ordering': ['-created'], 'verbose_name': 'PI', 'verbose_name_plural': 'PI'},
        ),
        migrations.RemoveField(
            model_name='pi',
            name='PI_area',
        ),
        migrations.RemoveField(
            model_name='pi',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pi',
            name='picture_after_rectification',
        ),
        migrations.RemoveField(
            model_name='pi',
            name='picture_before_rectification',
        ),
        migrations.AddField(
            model_name='pi',
            name='area',
            field=models.CharField(choices=[(b'completed', 'Completed'), (b'uncompleted', 'Uncompleted')], default=b'uncompleted', max_length=30, verbose_name='area'),
        ),
        migrations.AddField(
            model_name='pi',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rectification completed time'),
        ),
        migrations.AddField(
            model_name='pi',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 12, 9, 13, 6, 21, 165000, tzinfo=utc), verbose_name='Inspection Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pi',
            name='image_after',
            field=models.ImageField(default=None, max_length=30, upload_to=inspection.models.image_upload_to_pi, verbose_name='picture after rectification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pi',
            name='image_before',
            field=models.ImageField(default='', max_length=30, upload_to=inspection.models.image_upload_to_pi, verbose_name='picture before rectification'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pi',
            name='category',
            field=models.CharField(choices=[(b'PI', 'PI')], max_length=30, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='company_of_reporter',
            field=models.CharField(choices=[(b'SNT', 'SNT')], max_length=30, verbose_name='company of reporter'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='department_of_reporter',
            field=models.CharField(choices=[(b'security', 'security'), (b'storage', 'storage'), (b'administration', 'administration')], max_length=30, verbose_name='department of reporter'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='direct_reason',
            field=models.CharField(choices=[(b'unsafe_condition', 'unsafe condition')], max_length=30, verbose_name='direct reason'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='rectification_status',
            field=models.CharField(choices=[(b'completed', 'Completed'), (b'uncompleted', 'Uncompleted')], max_length=30, verbose_name='rectification status'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='report_content',
            field=models.TextField(max_length=500, verbose_name='report content'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='risk',
            field=models.CharField(choices=[(b'H', b'H'), (b'M', b'M'), (b'L', b'L')], max_length=30, verbose_name='risk'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='root_cause',
            field=models.CharField(choices=[(b'MM', 'MM'), (b'EC', 'EC')], max_length=30, verbose_name='root cause'),
        ),
    ]
