# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-09 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import inspection.models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0063_auto_20171209_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='image_after',
            field=models.ImageField(blank=True, max_length=30, null=True, upload_to=inspection.models.image_upload_to_pi, verbose_name='picture after rectification'),
        ),
    ]
