# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-09 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import inspection.models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0064_auto_20171209_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='area',
            field=models.CharField(choices=[(b'inwarehouse', 'in warehouse'), (b'outwarehouse', 'out warehouse')], default=b'inwarehouse', max_length=30, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='category',
            field=models.CharField(choices=[(b'PI', 'PI')], default=b'PI', max_length=30, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='company_of_reporter',
            field=models.CharField(choices=[(b'SNT', 'SNT')], default=b'SNT', max_length=30, verbose_name='company of reporter'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='department_of_reporter',
            field=models.CharField(choices=[(b'security', 'security'), (b'storage', 'storage'), (b'administration', 'administration')], default=b'storage', max_length=30, verbose_name='department of reporter'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='direct_reason',
            field=models.CharField(choices=[(b'unsafe_condition', 'unsafe condition')], default=b'unsafe_condition', max_length=30, verbose_name='direct reason'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='image_after',
            field=models.ImageField(blank=True, null=True, upload_to=inspection.models.image_upload_to_pi, verbose_name='picture after rectification'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='image_before',
            field=models.ImageField(blank=True, upload_to=b'pi', verbose_name='picture before rectification'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='rectification_measures',
            field=models.TextField(max_length=30, verbose_name='rectification measures'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='rectification_status',
            field=models.CharField(choices=[(b'completed', 'Completed'), (b'uncompleted', 'Uncompleted')], default=b'uncompleted', max_length=30, verbose_name='rectification status'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='risk',
            field=models.CharField(choices=[(b'H', b'H'), (b'M', b'M'), (b'L', b'L')], default=b'M', max_length=30, verbose_name='risk'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='root_cause',
            field=models.CharField(choices=[(b'MM', 'MM'), (b'EC', 'EC')], default=b'MM', max_length=30, verbose_name='root cause'),
        ),
    ]
