# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-09 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import inspection.models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0065_auto_20171209_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='close_person',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='close person'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='image_before',
            field=models.ImageField(upload_to=inspection.models.image_upload_to_pi, verbose_name='picture before rectification'),
        ),
    ]
