# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-10 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0066_auto_20171210_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfannualinspectionimage',
            name='image',
            field=models.ImageField(default='', upload_to=b'inspection/shelf_annual_inspection', verbose_name='image'),
            preserve_default=False,
        ),
    ]
