# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-13 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0067_auto_20171210_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelfannualinspectionimage',
            options={'verbose_name': 'shelf annual inspection image', 'verbose_name_plural': 'shelf annual inspection image'},
        ),
        migrations.AlterField(
            model_name='shelf_inspection_record',
            name='owner',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Owner'),
        ),
    ]
