# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-19 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0068_auto_20171214_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehearsal',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
    ]
