# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-23 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0071_auto_20171223_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hydrantinspection',
            old_name='extinguisher',
            new_name='hydrant',
        ),
        migrations.AddField(
            model_name='extinguisherinspection',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rectification completed time'),
        ),
        migrations.AddField(
            model_name='extinguisherinspection',
            name='forecast_complete_time',
            field=models.DateField(blank=True, null=True, verbose_name='Forecast Complete Time'),
        ),
        migrations.AddField(
            model_name='extinguisherinspection',
            name='owner',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='hydrantinspection',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rectification completed time'),
        ),
        migrations.AddField(
            model_name='hydrantinspection',
            name='forecast_complete_time',
            field=models.DateField(blank=True, null=True, verbose_name='Forecast Complete Time'),
        ),
        migrations.AddField(
            model_name='hydrantinspection',
            name='owner',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='extinguisherinspection',
            name='check_date',
            field=models.DateField(auto_now_add=True, verbose_name='Check Date'),
        ),
        migrations.AlterField(
            model_name='hydrantinspection',
            name='check_date',
            field=models.DateField(auto_now_add=True, verbose_name='Check Date'),
        ),
    ]
