# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-23 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0072_auto_20171223_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extinguisher',
            name='capacity',
        ),
        migrations.AddField(
            model_name='extinguisherinspection',
            name='capacity',
            field=models.CharField(blank=True, max_length=30, verbose_name='Capacity'),
        ),
    ]
