# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-23 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0074_auto_20171223_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydrantinspection',
            name='check_date',
        ),
        migrations.RemoveField(
            model_name='hydrantinspection',
            name='check_person',
        ),
        migrations.RemoveField(
            model_name='hydrantinspection',
            name='check_result',
        ),
        migrations.RemoveField(
            model_name='hydrantinspection',
            name='completed_time',
        ),
        migrations.RemoveField(
            model_name='hydrantinspection',
            name='forecast_complete_time',
        ),
        migrations.RemoveField(
            model_name='hydrantinspection',
            name='owner',
        ),
    ]
