# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-23 06:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0075_auto_20171223_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrantinspection',
            name='check_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 12, 23, 6, 41, 21, 29000, tzinfo=utc), verbose_name='Check Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hydrantinspection',
            name='check_person',
            field=models.CharField(blank=True, max_length=30, verbose_name='Check Person'),
        ),
        migrations.AddField(
            model_name='hydrantinspection',
            name='check_result',
            field=models.CharField(blank=True, choices=[(b'normal', 'Normal'), (b'breakdown', 'Breakdown')], max_length=30, verbose_name='Check Result'),
        ),
        migrations.AddField(
            model_name='hydrantinspection',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rectification completed time'),
        ),
        migrations.AddField(
            model_name='hydrantinspection',
            name='forecast_complete_time',
            field=models.DateField(blank=True, null=True, verbose_name='Forecast Complete Time'),
        ),
        migrations.AddField(
            model_name='hydrantinspection',
            name='owner',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Owner'),
        ),
    ]
