# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-01 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0078_auto_20171230_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extinguisherinspection',
            old_name='forecast_complete_time',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='hydrantinspection',
            old_name='forecast_complete_time',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='shelf_inspection_record',
            old_name='forecast_complete_time',
            new_name='due_date',
        ),
    ]
