# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-01 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0079_auto_20180101_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extinguisherinspection',
            old_name='check_person',
            new_name='inspector',
        ),
        migrations.RenameField(
            model_name='hydrantinspection',
            old_name='check_person',
            new_name='inspector',
        ),
        migrations.RenameField(
            model_name='shelf_inspection_record',
            old_name='check_person',
            new_name='inspector',
        ),
    ]
