# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-01 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0080_auto_20180101_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf_inspection',
            name='check_date',
            field=models.DateField(auto_now_add=True, unique=True, verbose_name='Check Date'),
        ),
    ]
