# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-01 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0081_auto_20180101_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rtpi',
            old_name='planned_complete_date',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='whpi',
            old_name='planned_complete_date',
            new_name='due_date',
        ),
    ]
