# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-14 07:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0083_auto_20180106_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, help_text='Use the following format: < YYYY >', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2019)], verbose_name='year')),
                ('owner', models.CharField(max_length=30, verbose_name='owner')),
                ('supporter', models.CharField(max_length=30, verbose_name='supporter')),
                ('jan', models.CharField(blank=True, choices=[(b'on schedue', 'on schedue'), (b'overdue', 'overdue'), (b'completed', 'completed')], max_length=30, null=True, verbose_name='January')),
                ('feb', models.CharField(blank=True, choices=[(b'on schedue', 'on schedue'), (b'overdue', 'overdue'), (b'completed', 'completed')], max_length=30, null=True, verbose_name='February')),
                ('mar', models.CharField(blank=True, choices=[(b'on schedue', 'on schedue'), (b'overdue', 'overdue'), (b'completed', 'completed')], max_length=30, null=True, verbose_name='March')),
                ('apr', models.CharField(blank=True, choices=[(b'on schedue', 'on schedue'), (b'overdue', 'overdue'), (b'completed', 'completed')], max_length=30, null=True, verbose_name='April')),
                ('may', models.CharField(blank=True, choices=[(b'on schedue', 'on schedue'), (b'overdue', 'overdue'), (b'completed', 'completed')], max_length=30, null=True, verbose_name='May')),
                ('jun', models.CharField(blank=True, choices=[(b'on schedue', 'on schedue'), (b'overdue', 'overdue'), (b'completed', 'completed')], max_length=30, null=True, verbose_name='June')),
                ('jul', models.CharField(blank=True, choices=[(b'on schedue', 'on schedue'), (b'overdue', 'overdue'), (b'completed', 'completed')], max_length=30, null=True, verbose_name='July')),
                ('aug', models.CharField(blank=True, choices=[(b'on schedue', 'on schedue'), (b'overdue', 'overdue'), (b'completed', 'completed')], max_length=30, null=True, verbose_name='August')),
                ('sep', models.CharField(blank=True, choices=[(b'on schedue', 'on schedue'), (b'overdue', 'overdue'), (b'completed', 'completed')], max_length=30, null=True, verbose_name='September')),
                ('oct', models.CharField(blank=True, choices=[(b'on schedue', 'on schedue'), (b'overdue', 'overdue'), (b'completed', 'completed')], max_length=30, null=True, verbose_name='October')),
                ('nov', models.CharField(blank=True, choices=[(b'on schedue', 'on schedue'), (b'overdue', 'overdue'), (b'completed', 'completed')], max_length=30, null=True, verbose_name='November')),
                ('dec', models.CharField(blank=True, choices=[(b'on schedue', 'on schedue'), (b'overdue', 'overdue'), (b'completed', 'completed')], max_length=30, null=True, verbose_name='December')),
            ],
            options={
                'verbose_name': 'annual plan',
                'verbose_name_plural': 'annual plan',
            },
        ),
        migrations.CreateModel(
            name='AnnualPlanCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, verbose_name='categoy')),
            ],
            options={
                'verbose_name': 'annual plan category',
                'verbose_name_plural': 'annual plan category',
            },
        ),
        migrations.AddField(
            model_name='annualplan',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.AnnualPlanCategory', verbose_name='category'),
        ),
    ]
