# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-14 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0084_auto_20180114_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualplan',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
