# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-14 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0085_annualplan_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualplan',
            name='title',
            field=models.CharField(max_length=130, verbose_name='Title'),
        ),
    ]
