# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_electricalequipmentinspection_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipment'},
        ),
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'verbose_name': 'Equipment Type', 'verbose_name_plural': 'Equipment Type'},
        ),
        migrations.AlterField(
            model_name='electricalequipmentinspection',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.Equipment', verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='electricalequipmentinspection',
            name='use_condition',
            field=models.CharField(choices=[('1', 'Normal'), ('2', 'Breakdown')], default='normal', max_length=30, verbose_name='Use Condition'),
        ),
    ]
