# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_auto_20171025_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricalequipmentinspection',
            name='use_condition',
            field=models.CharField(choices=[('normal', 'Normal'), ('breakdown', 'Breakdown')], default='normal', max_length=30, verbose_name='Use Condition'),
        ),
    ]
