# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-26 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_auto_20171025_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_condition', models.CharField(choices=[('normal', 'Normal'), ('breakdown', 'Breakdown')], default='normal', max_length=30, verbose_name='Use Condition')),
                ('inspector', models.CharField(max_length=30, verbose_name='Inspector')),
                ('comments', models.TextField(blank=True, max_length=130, verbose_name='Comments')),
                ('date_of_inspection', models.DateField(verbose_name='Date of Inspection')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.Equipment', verbose_name='Equipment')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Equipment Inspection',
                'verbose_name_plural': 'Equipment Inspection',
            },
        ),
        migrations.AlterModelOptions(
            name='electricalequipmentinspection',
            options={'verbose_name': 'Equipment Inspection', 'verbose_name_plural': 'Equipment Inspection'},
        ),
    ]
