# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-26 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_auto_20171026_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricalequipmentinspection',
            name='equipment',
        ),
        migrations.DeleteModel(
            name='ElectricalEquipmentInspection',
        ),
    ]
