# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-01 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_auto_20171026_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprayPumpRoomInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[(b'1jan', 'January'), (b'2feb', 'February'), (b'3mar', 'March'), (b'4apr', 'April'), (b'5may', 'May'), (b'6jun', 'June'), (b'7jul', 'July'), (b'8aug', 'August'), (b'9sep', 'September'), (b'aoct', 'October'), (b'bnov', 'November'), (b'cdev', 'December')], max_length=30, verbose_name='Month')),
                ('voltage_and_power_normal', models.BooleanField(default=False, verbose_name='voltage and power normal')),
                ('indicator_and_instrument_normal', models.BooleanField(default=False, verbose_name='indicator and instrument normal')),
                ('inspector', models.CharField(max_length=30, verbose_name='Inspector')),
                ('date_of_inspection', models.DateField(default='1970-01-01', verbose_name='Date of Inspection')),
            ],
            options={
                'ordering': ('month',),
                'verbose_name': 'Spray Pump Room Inspection',
                'verbose_name_plural': 'Spray Pump Room Inspection',
            },
        ),
    ]
