# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-02 14:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0009_auto_20171102_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='spraypumproominspection',
            name='motor_and_pump_connection_intact',
            field=models.BooleanField(default=False, verbose_name='motor and pump connection intact'),
        ),
        migrations.AddField(
            model_name='spraypumproominspection',
            name='motor_sample_integrated',
            field=models.BooleanField(default=False, verbose_name='motor sample integrated'),
        ),
        migrations.AddField(
            model_name='spraypumproominspection',
            name='no_corrosion_and_damage',
            field=models.BooleanField(default=False, verbose_name='no corrosion and damage'),
        ),
        migrations.AddField(
            model_name='spraypumproominspection',
            name='no_corrosion_inside_and_foundation_bolt_not_loose',
            field=models.BooleanField(default=False, verbose_name='no corrosion inside and foundation bolt not loose'),
        ),
        migrations.AddField(
            model_name='spraypumproominspection',
            name='no_sundries_in_pump_house',
            field=models.BooleanField(default=False, verbose_name='no sundries in pump house'),
        ),
        migrations.AddField(
            model_name='spraypumproominspection',
            name='one_way_valve_intact_and_no_leak_and_pressure_gage_normal',
            field=models.BooleanField(default=False, verbose_name='one-way valve intact and no leak and pressure gage normal'),
        ),
        migrations.AddField(
            model_name='spraypumproominspection',
            name='pool_wall_dry_and_no_leak',
            field=models.BooleanField(default=False, verbose_name='pool wall dry and no leak'),
        ),
        migrations.AddField(
            model_name='spraypumproominspection',
            name='pressure_maintaining_valve_intact',
            field=models.BooleanField(default=False, verbose_name='pressure maintaining valve intact'),
        ),
        migrations.AddField(
            model_name='spraypumproominspection',
            name='pump_house_clean_and_tidy',
            field=models.BooleanField(default=False, verbose_name='pump house clean and tidy'),
        ),
        migrations.AddField(
            model_name='spraypumproominspection',
            name='switch_contactor_and_connection_normal',
            field=models.BooleanField(default=False, verbose_name='switch contactor and connection normal'),
        ),
        migrations.AddField(
            model_name='spraypumproominspection',
            name='valve_normally_open',
            field=models.BooleanField(default=False, verbose_name='valve normally open'),
        ),
        migrations.AddField(
            model_name='spraypumproominspection',
            name='water_level_cover_plate_and_no_abnormal_move',
            field=models.BooleanField(default=False, verbose_name='water level cover plate and no abnormal move'),
        ),
        migrations.AddField(
            model_name='spraypumproominspection',
            name='water_level_normal_and_moisturizing_well',
            field=models.BooleanField(default=False, verbose_name='water level normal and moisturizing well'),
        ),
        migrations.AlterField(
            model_name='spraypumproominspection',
            name='year',
            field=models.PositiveIntegerField(help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(2017), django.core.validators.MaxValueValidator(2017)], verbose_name='year'),
        ),
    ]
