# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-05 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0010_auto_20171102_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spraypumproominspection',
            name='month',
            field=models.CharField(choices=[(b'01', 'January'), (b'02', 'February'), (b'03', 'March'), (b'04', 'April'), (b'05', 'May'), (b'06', 'June'), (b'07', 'July'), (b'08', 'August'), (b'09', 'September'), (b'10', 'October'), (b'11', 'November'), (b'12', 'December')], max_length=30, verbose_name='Month'),
        ),
    ]
