# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-11 01:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0011_auto_20171105_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spraypumproominspection',
            name='year',
            field=models.PositiveIntegerField(help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2017)], verbose_name='year'),
        ),
    ]
