# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0013_auto_20171111_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinspection',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='updated'),
        ),
    ]
