# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-03 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0017_auto_20171203_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinspection',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Latest Update'),
        ),
        migrations.AlterField(
            model_name='spraypumproominspection',
            name='date_of_inspection',
            field=models.DateField(auto_now_add=True, verbose_name='Date of Inspection'),
        ),
    ]
