# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-07 05:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import inspection.utils


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0019_auto_20171206_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSSEKPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Use the following format: < YYYY >', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2017)], verbose_name='year')),
                ('month', models.CharField(choices=[(b'01', 'January'), (b'02', 'February'), (b'03', 'March'), (b'04', 'April'), (b'05', 'May'), (b'06', 'June'), (b'07', 'July'), (b'08', 'August'), (b'09', 'September'), (b'10', 'October'), (b'11', 'November'), (b'12', 'December')], max_length=30, verbose_name='Month')),
                ('LTI', models.PositiveIntegerField(default=0, verbose_name='LTI')),
                ('RWC', models.PositiveIntegerField(default=0, verbose_name='RWC - restricted working cases')),
                ('MTC', models.PositiveIntegerField(default=0, verbose_name='MTC - medical treatment cases')),
                ('FAC', models.PositiveIntegerField(default=0, verbose_name='FAC')),
                ('LPOC', models.PositiveIntegerField(default=0, verbose_name='LPOC')),
                ('cargo_lost_liter', models.PositiveIntegerField(default=0, verbose_name='cargo lost liter')),
                ('TRC', models.PositiveIntegerField(default=0, verbose_name='TRC')),
                ('LSR_violation_case_count', models.PositiveIntegerField(default=0, verbose_name='LSR violation case count')),
                ('PI_NM_reported_count', models.PositiveIntegerField(default=0, verbose_name='PI NM reported count')),
                ('best_PI_NM_report_count', models.PositiveIntegerField(default=0, verbose_name='best PI NM report count')),
                ('PI_NM_close_rate', inspection.utils.PercentageField(default='0%', max_length=30, verbose_name='PI NM close rate')),
                ('leadship_SSWT_ongoing_count', models.PositiveIntegerField(default=0, verbose_name='leadship SSWT ongoing count')),
                ('leadship_SSWT_close_rate', inspection.utils.PercentageField(default='0%', max_length=30, verbose_name='leadship SSWT close rate')),
                ('annual_plan_execution_rate', inspection.utils.PercentageField(default='0%', max_length=30, verbose_name='annual plan execution rate')),
                ('save_working_hours', models.PositiveIntegerField(default=0, verbose_name='save working hours')),
                ('inspector', models.CharField(max_length=30, verbose_name='Inspector')),
                ('date_of_inspection', models.DateField(auto_now_add=True, verbose_name='Date of Inspection')),
            ],
            options={
                'ordering': ('month',),
                'verbose_name': 'HSSE KPI',
                'verbose_name_plural': 'HSSE KPI',
            },
        ),
        migrations.AlterUniqueTogether(
            name='hssekpi',
            unique_together=set([('month', 'year')]),
        ),
    ]
