# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-21 11:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0020_auto_20171207_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spraypumproominspection',
            name='year',
            field=models.PositiveIntegerField(help_text='Use the following format: < YYYY >', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2018)], verbose_name='year'),
        ),
    ]
