# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-01 12:38
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0022_auto_20171221_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='spraypumproominspection',
            name='owner',
            field=models.CharField(default='', max_length=30, verbose_name='Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spraypumproominspection',
            name='rectification_status',
            field=models.CharField(choices=[(b'completed', 'Completed'), (b'uncompleted', 'Uncompleted')], default='uncompleted', max_length=30, verbose_name='Rectification Status'),
        ),
        migrations.AddField(
            model_name='spraypumproominspection',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 1, 1, 12, 37, 50, 179000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spraywarehouseinspection',
            name='owner',
            field=models.CharField(default='', max_length=30, verbose_name='Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spraywarehouseinspection',
            name='rectification_status',
            field=models.CharField(choices=[(b'completed', 'Completed'), (b'uncompleted', 'Uncompleted')], default='uncompleted', max_length=30, verbose_name='Rectification Status'),
        ),
        migrations.AddField(
            model_name='spraywarehouseinspection',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 1, 1, 12, 38, 0, 411000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hssekpi',
            name='year',
            field=models.PositiveIntegerField(help_text='Use the following format: < YYYY >', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2019)], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='spraypumproominspection',
            name='year',
            field=models.PositiveIntegerField(help_text='Use the following format: < YYYY >', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2019)], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='spraywarehouseinspection',
            name='year',
            field=models.PositiveIntegerField(help_text='Use the following format: < YYYY >', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2019)], verbose_name='year'),
        ),
    ]
