# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-01 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0023_auto_20180101_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentinspection',
            old_name='date_of_inspection',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='hssekpi',
            old_name='date_of_inspection',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='spraypumproominspection',
            old_name='date_of_inspection',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='spraywarehouseinspection',
            old_name='date_of_inspection',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='spraypumproominspection',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='spraywarehouseinspection',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
    ]
