# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-01 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='score')),
                ('work_position', models.CharField(choices=[(b'driver', 'driver'), (b'forklift driver', 'forklift driver'), (b'project manager', 'project manager')], max_length=30, verbose_name='work position')),
            ],
        ),
        migrations.RemoveField(
            model_name='trainingcourse',
            name='type',
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='category',
            field=models.CharField(choices=[(b'work license', 'work license'), (b'annual training plan', 'annual training plan'), (b'meeting before work', 'meeting before work'), (b'other', 'other')], default='work licnese', max_length=150, verbose_name='training category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annualtraningplan',
            name='actual_date',
            field=models.DateField(blank=True, null=True, verbose_name='actual date'),
        ),
        migrations.AlterField(
            model_name='annualtraningplan',
            name='planned_date',
            field=models.DateField(verbose_name='planned date'),
        ),
        migrations.AlterField(
            model_name='annualtraningplan',
            name='training_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.TrainingCourse', verbose_name='training'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='training content'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='date',
            field=models.DateField(verbose_name='training date'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='location',
            field=models.CharField(max_length=30, verbose_name='training location'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='topic',
            field=models.CharField(max_length=150, verbose_name='training topic'),
        ),
        migrations.AddField(
            model_name='trainingperson',
            name='training_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.TrainingCourse', verbose_name='training'),
        ),
    ]
