# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-01 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_auto_20171101_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annualtraningplan',
            options={'verbose_name': 'annual training plan', 'verbose_name_plural': 'annual training plan'},
        ),
        migrations.AlterModelOptions(
            name='trainingcourse',
            options={'verbose_name': 'training course', 'verbose_name_plural': 'training courses'},
        ),
        migrations.AlterModelOptions(
            name='trainingperson',
            options={'verbose_name': 'training person', 'verbose_name_plural': 'training persons'},
        ),
        migrations.AddField(
            model_name='trainingperson',
            name='trainee',
            field=models.CharField(default='', max_length=30, verbose_name='trainee'),
            preserve_default=False,
        ),
    ]
