# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-11 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_auto_20171101_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='training date')),
                ('location', models.CharField(max_length=30, verbose_name='training location')),
                ('trainer', models.CharField(max_length=30, verbose_name='trainer')),
                ('audiences', models.CharField(max_length=30, verbose_name='audiences')),
                ('annual_trainning_pan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.AnnualTraningPlan', verbose_name='annual training plan')),
            ],
            options={
                'verbose_name': 'training record',
                'verbose_name_plural': 'training record',
            },
        ),
        migrations.CreateModel(
            name='TrainingTranscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee', models.CharField(max_length=30, verbose_name='trainee')),
                ('score', models.PositiveIntegerField(verbose_name='score')),
                ('work_position', models.CharField(choices=[(b'driver', 'driver'), (b'forklift driver', 'forklift driver'), (b'project manager', 'project manager')], max_length=30, verbose_name='work position')),
            ],
            options={
                'verbose_name': 'training transcript',
                'verbose_name_plural': 'training transcript',
            },
        ),
        migrations.RemoveField(
            model_name='trainingperson',
            name='training_course',
        ),
        migrations.RemoveField(
            model_name='trainingcourse',
            name='date',
        ),
        migrations.RemoveField(
            model_name='trainingcourse',
            name='location',
        ),
        migrations.DeleteModel(
            name='TrainingPerson',
        ),
        migrations.AddField(
            model_name='trainingtranscript',
            name='training_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.TrainingCourse', verbose_name='training course'),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='training_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.TrainingCourse', verbose_name='training course'),
        ),
    ]
