# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-11 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_auto_20171111_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingtranscript',
            name='training_course',
        ),
        migrations.AddField(
            model_name='trainingtranscript',
            name='training_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainings.TrainingRecord', verbose_name='training record'),
            preserve_default=False,
        ),
    ]
