# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-11 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_auto_20171111_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingrecord',
            name='annual_trainning_pan',
        ),
        migrations.AddField(
            model_name='annualtraningplan',
            name='training_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.TrainingRecord', verbose_name='training_record'),
        ),
    ]
