# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-12 01:58
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_auto_20171111_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualtraningplan',
            name='training_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.TrainingRecord', verbose_name='training record'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='training content'),
        ),
    ]
