# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-12 02:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0008_auto_20171112_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualtraningplan',
            name='year',
            field=models.PositiveIntegerField(default=2017, help_text='Use the following format: < YYYY >', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2017)], verbose_name='year'),
            preserve_default=False,
        ),
    ]
