# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-03 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0009_annualtraningplan_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='training_class',
            field=models.CharField(choices=[(b'warehouse', 'warehouse'), (b'transportation', 'transportation')], default=b'warehouse', max_length=150, verbose_name='training class'),
        ),
    ]
