# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-30 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0011_auto_20171221_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='sign_sheet',
            field=models.FileField(blank=True, upload_to=b'training', verbose_name='sign sheet'),
        ),
    ]
