# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-01 12:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0012_trainingrecord_sign_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualtraningplan',
            name='year',
            field=models.PositiveIntegerField(help_text='Use the following format: < YYYY >', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2019)], verbose_name='year'),
        ),
    ]
