# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('picking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickingBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='number')),
                ('product_id', models.CharField(blank=True, max_length=30, verbose_name='product id')),
                ('product_name', models.CharField(blank=True, max_length=30, verbose_name='product name')),
                ('dispatch_bill_number', models.CharField(blank=True, max_length=30, verbose_name='dispatch bill number')),
                ('waybill_number', models.CharField(blank=True, max_length=30, verbose_name='waybill number')),
                ('product_total_number', models.IntegerField(blank=True, verbose_name='product total number')),
                ('packing_total_number', models.IntegerField(blank=True, verbose_name='packing total number')),
                ('status', models.CharField(blank=True, max_length=30, verbose_name='status')),
                ('created', models.DateField(verbose_name='created date')),
            ],
            options={
                'ordering': ['number'],
                'verbose_name': 'packing bill',
                'verbose_name_plural': 'packing bill',
            },
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='number')),
                ('forwarder', models.CharField(blank=True, max_length=30, verbose_name='forwarder')),
                ('product_number', models.IntegerField(blank=True, verbose_name='product number')),
                ('packing_number', models.IntegerField(blank=True, verbose_name='packing number')),
            ],
            options={
                'ordering': ['number'],
                'verbose_name': 'waybill',
                'verbose_name_plural': 'waybill',
            },
        ),
        migrations.AddField(
            model_name='pickingbill',
            name='waybill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picking.Waybill', verbose_name='waybill'),
        ),
    ]
