# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picking', '0002_auto_20171121_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickingbill',
            name='volume',
            field=models.IntegerField(blank=True, default=0, verbose_name='volume'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waybill',
            name='volume',
            field=models.IntegerField(blank=True, default=1, verbose_name='volume'),
            preserve_default=False,
        ),
    ]
