# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picking', '0004_auto_20171121_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickingbill',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='created date'),
        ),
    ]
