# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-25 02:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('picking', '0007_auto_20171121_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickingbill',
            options={'ordering': ['number'], 'verbose_name': 'picking bill', 'verbose_name_plural': 'picking bill'},
        ),
        migrations.AddField(
            model_name='pickingbill',
            name='assigned',
            field=models.DateField(default=datetime.datetime(2017, 11, 25, 2, 22, 33, 123000, tzinfo=utc), verbose_name='assigned date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waybill',
            name='completed',
            field=models.DateField(default=datetime.datetime(2017, 11, 25, 2, 22, 41, 721000, tzinfo=utc), verbose_name='completed date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waybill',
            name='created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 11, 25, 2, 22, 48, 662000, tzinfo=utc), verbose_name='created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waybill',
            name='status',
            field=models.CharField(blank=True, max_length=30, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='pickingbill',
            name='number',
            field=models.CharField(blank=True, max_length=30, verbose_name='pickingbill number'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='number',
            field=models.CharField(blank=True, max_length=30, verbose_name='waybill number'),
        ),
    ]
