# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-25 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picking', '0008_auto_20171125_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickingbill',
            name='assigned',
            field=models.DateTimeField(verbose_name='assigned time'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='completed',
            field=models.DateTimeField(verbose_name='completed time'),
        ),
    ]
